### ISSUE TITLE
Reconsider ordering of information

### ISSUE THREAD

**Issue by tklebel** [CWTSLeiden/Journal-Observatory-Browser#61]
The information provided for a certain journal, e.g. [this one](https://app.journalobservatory.org/pad/e2e73142-5b39-459c-9557-92efab4249cf), starts with the name, identifiers, and publishers. However, given the target audience (researchers trying to gather information on the various policies) it might make sense to reorder them, starting with the policies, and then providing the more technical metadata. This would make it more useful, in my view.

**Comment by bramboomen** [comment]
Thanks for the suggestion Thomas! We debated it for a bit but we decided that we wanted to keep the current order of information. However, we do agree that there is too much information to scroll through before you get to the policies. So we decided to make all the blocks collapsible and to collapse the 'Names' and 'Identifiers' blocks by default. This change should be live in the web-app soon.
